production:
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      address: "172.17.0.1"
      port: 25
      domain: "myredmine.localhost"
 
  rmagick_font_path: /usr/share/fonts/ipa-pgothic/ipagp.ttf
